### ISSUE TITLE
Custom serializer output is html entity encoded

### ISSUE THREAD

**Issue by raine** [sanity-io/block-content-to-markdown#2]
I have code roughly as:

```
const renderCtaButtonToMarkdown = ({ node: { linkUrl, text } }: any): string =>
  `[${text}](${linkUrl})`

const bodyText = blocksToMarkdown(bodyBlocks, {
  serializers: {
    types: {
      ctaButton: renderCtaButtonToMarkdown
    }
  }
})
```

Which gives the output

```
[My text](http:&#x2F;&#x2F;localhost:3000&#x2F;foo&#x2F;bar)
```

There seems to be some kind of undocumented behavior that "dangerous" characters are getting html entity encoded. How do I disable this? My values come from the CMS so I can assume them to be safe, especially in this context.

**Comment by kmelve** [comment]
Thanks for reporting! I must admit I haven't seen this behaviour from this package before. [I can't reproduce it either](https://codesandbox.io/s/render-portable-text-to-markdown-6lfph). Could you give us some more details of what environment you are it etc?

**Comment by raine** [comment]
Looks like I spoke to soon thinking this was related to https://github.com/sanity-io/block-content-to-html/issues/3 somehow, where I had actual problem. In this case I didn't realize it was actually mustache.js escaping the link because of double curly braces. 🤦‍♂ 

Apologies for the noise.

**Comment by kmelve** [comment]
That’s ok :) let us know if you hit any problems!
